export const FILE_PATHS = {
  DTS_COLLECTION: "app/data/2023-08/collection.json",
  DEFINITIONS: "app/data/pal/definitions-digipal.json",
  VARIANT_RULES: "app/data/variant-rules.json",
  // CHANGE_QUEUE: "annotations/change-queue.json",
  CHANGE_QUEUE: "app/data/change-queue.json",
  // TODO: move them under data folder
  INDEX: "app/index.json",
  ANNOTATIONS_ISSUES: "app/data/annotations-issues.json",
  INDEX_COLLECTION: "app/data/index-collection.json",
  STATS: "app/stats.json",
  THUMBS: "app/data/thumbs",
  INDEX_THUMBS: "app/data/thumbs/thumbs.json",
  ANNOTATIONS: "app/annotations",
}

// list generated by J. Prag with ChatGPT
// see email from Fr 03/10/2025
const PLACES_IN_DISPLAY_ORDER = `
Imachara
Tauromenium
Naxos
Aetna mons
Mendolito
Agyrium
Adranon
Assorus
Centuripae
Inessa-Aetna
Acium
Aetna
Hybla Gereatis
Inessa
Catina
Enna
Brikinniai
Capitoniania
Leontini
Megara Hyblaea
Morgantina
Palikè
Syracusae
Styella
Menae
Herbessus
Piazza Armerina
Acrae
Euboia
Kasmenai
Netum
Helorus
Pachynus
Acrillae
Hybla Heraea
Mutyca
Dianae Fons
Bidis
Philosophiana
Kaukana
Kamarina
Gela
Melita
Gaulus
Kakyron
Phintias
Motyon
Agrigentum
Cossura
Thermae Selinuntiae
Selinus
Mazara
Lilybaeum
Motya
Hippana
Halicyae
Aegusa, Aegates Islands
Aegusa
Entella
Phorbantia, Aegates Islands
Drepanum
Segesta
Eryx
Aquae Segestanae
Ietas
Parthenicum
Panhormus
Soluntum
Thermae Himeraeae
Ustica
Himera
Cephaloedium
Phoenicusa
Halaesa
Didyme
Euonymus
Lipara
Amestratus
Agathyrnum
Calacte
Apollonia
Haluntium
Tyndaris
Capitium
Mylai
Longane
Abacaenum
Messana
`

// TODO: move all hard-coded literals in the code base to this SETTINGS dictionary
export const SETTINGS = {
  // TODO: search this string & replace everywhere
  GITHUB_REPO_PATH: "kingsdigitallab/crossreads",
  // if you change this you"ll need to empty the content of the app/data/thumbs folder
  // then re-run tools/index.mjs to obtain the new sizes
  EXEMPLAR_THUMB_HEIGHT: 150,
  APPLICATION_TABS: [
    {title: "Annotator", key: "annotator"},
    {title: "Definitions", key: "definitions"},
    {title: "Search", key: "search"},
    {title: "Lab", key: "lab"},
    {title: "Settings", key: "settings"},
  ],
  BROWSER_STORAGE_INSCRIPTION_SETS: "inscriptionSets",
  CORPUS_BUILDING_INSCRIPTION_URL: "https://kingsdigitallab.github.io/corpus-building/inscription/{docId}",
  // Corresponds to {scheme}://{server}{/prefix} in IIIF Image API
  IIIF_SERVER_BASE: "https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=",
  // IIIF_SERVER_BASE: "http://localhost:4000/images", // for TESTING ONLY
  IIIF_SERVER_OBJ_ID: "/inscription_images/{DOCID}/{IMGID}",
  DTS_COLLECTION: "https://raw.githubusercontent.com/ISicily/ISicily/master/dts/collection.json",
  DTS_DOC_BASE: "http://sicily.classics.ox.ac.uk/inscription/",
  // convert PLACES_IN_DISPLAY_ORDER into a list
  PLACES_IN_DISPLAY_ORDER: PLACES_IN_DISPLAY_ORDER.split("\n").map(p => p.trim()).filter(p => p.length),
  XPATH_TRANSCRIPTION_IN_TEI: "//tei:body/tei:div[@type='edition'][not(@subtype) or @subtype='transcription']",
  XPATH_TOKENS_IN_TEI: "//*[name()!='l'][name()!='lg'][name()!='lb'][name()!='cb'][name()!='milestone'][not(@type='textpart')]", // [@n='5']
  EXPECTED_TOKEN_TAGS: ['w', 'g', 'space', 'gap', 'orig'],
}
SETTINGS.GITHUB_REPO_URL = `https://github.com/${SETTINGS.GITHUB_REPO_PATH}`
