// Paths to all the data files.
// All paths relative to the code base root.
export const FILE_PATHS = {
  // DTS sub-collection for the annotator
  DTS_COLLECTION: "app/data/2023-08/collection.json",
  // array of IDs for the inscriptions to extract from full DTS collection
  INSCRIPTIONS_IDS: "app/data/2023-08/inscriptions.json",
  // TODO: rename that, no longer a digipal def
  DEFINITIONS: "app/data/pal/definitions-digipal.json",
  VARIANT_RULES: "app/data/variant-rules.json",
  // CHANGE_QUEUE: "annotations/change-queue.json",
  CHANGE_QUEUE: "app/data/change-queue.json",
  // TODO: move them under data folder
  INDEX: "app/index.json",
  ANNOTATIONS_ISSUES: "app/data/annotations-issues.json",
  INDEX_COLLECTION: "app/data/index-collection.json",
  STATS: "app/stats.json",
  THUMBS: "app/data/thumbs",
  INDEX_THUMBS: "app/data/thumbs/thumbs.json",
  ANNOTATIONS: "annotations",
}

// Ancient names of the places of origin of the inscriptions.
// This list is ordered by geographical proximity.
// following an anti-clockwise trajectory round the island.
// The list was generated by J. Prag with ChatGPT.
// The names MUST match those found in 
// //tei:msDesc/tei:history/tei:origin/tei:origPlace/tei:placeName[@type='ancient']/text()
// See email from Fr 03/10/2025.
const PLACES_IN_DISPLAY_ORDER = `
Imachara
Tauromenium
Naxos
Aetna mons
Mendolito
Agyrium
Adranon
Assorus
Centuripae
Inessa-Aetna
Acium
Aetna
Hybla Gereatis
Inessa
Catina
Enna
Brikinniai
Capitoniania
Leontini
Megara Hyblaea
Morgantina
Palikè
Syracusae
Styella
Menae
Herbessus
Piazza Armerina
Acrae
Euboia
Kasmenai
Netum
Helorus
Pachynus
Acrillae
Hybla Heraea
Mutyca
Dianae Fons
Bidis
Philosophiana
Kaukana
Kamarina
Gela
Melita
Gaulus
Kakyron
Phintias
Motyon
Agrigentum
Cossura
Thermae Selinuntiae
Selinus
Mazara
Lilybaeum
Motya
Hippana
Halicyae
Aegusa, Aegates Islands
Aegusa
Entella
Phorbantia, Aegates Islands
Drepanum
Segesta
Eryx
Aquae Segestanae
Ietas
Parthenicum
Panhormus
Soluntum
Thermae Himeraeae
Ustica
Himera
Cephaloedium
Phoenicusa
Halaesa
Didyme
Euonymus
Lipara
Amestratus
Agathyrnum
Calacte
Apollonia
Haluntium
Tyndaris
Capitium
Mylai
Longane
Abacaenum
Messana
`

// TODO: move all hard-coded literals in the code base to this SETTINGS dictionary
export const SETTINGS = {
  // The github repository path that contains the data files
  // (annotations, index, ...)
  // Change this to null to read all data files from the site, 
  // outside of github.
  // See docs/portability.md for details.
  // GITHUB_REPO_PATH: "kingsdigitallab/crossreads",
  GITHUB_REPO_PATH: null,
  // Path (relative to code base root) to the parent folder of the web application
  HTTP_PATHS_PREFIX: "app/",
  // The root URL of the annotating environment site
  ANNOTATING_SITE_ROOT: "https://kingsdigitallab.github.io/crossreads/",
  // if you change this you"ll need to empty the content of the app/data/thumbs folder
  // then re-run tools/index.mjs to obtain the new sizes
  EXEMPLAR_THUMB_HEIGHT: 150,
  APPLICATION_TABS: [
    {title: "Annotator", key: "annotator"},
    {title: "Definitions", key: "definitions"},
    {title: "Search", key: "search"},
    {title: "Lab", key: "lab"},
    {title: "Settings", key: "settings"},
  ],
  BROWSER_STORAGE_INSCRIPTION_SETS: "inscriptionSets",
  CORPUS_BUILDING_INSCRIPTION_URL: "https://kingsdigitallab.github.io/corpus-building/inscription/{docId}",
  // Corresponds to {scheme}://{server}{/prefix} in IIIF Image API
  IIIF_SERVER_BASE: "https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=",
  // IIIF_SERVER_BASE: "http://localhost:4000/images", // for TESTING ONLY
  IIIF_SERVER_OBJ_ID: "/inscription_images/{DOCID}/{IMGID}",
  DTS_COLLECTION: "https://raw.githubusercontent.com/ISicily/ISicily/master/dts/collection.json",
  // TODO: ideally we shouldn't hard code this, see gh-61
  // https://github.com/kingsdigitallab/crossreads/issues/61#issuecomment-3385499237
  // the value comes from the DTS collection and is stored in the annotation
  DTS_DOC_BASE: "http://sicily.classics.ox.ac.uk/inscription/",
  // The prefix of the URI of every annotation, found in the annotation files
  ANNOTATION_URI_PREFIX: "https://sicily.classics.ox.ac.uk/annotations/",
  // where this site sends user for general Crossreads site
  CROSSREADS_PORTAL_ROOT: "https://crossreads.web.ox.ac.uk/",
  // convert PLACES_IN_DISPLAY_ORDER into a list
  PLACES_IN_DISPLAY_ORDER: PLACES_IN_DISPLAY_ORDER.split("\n").map(p => p.trim()).filter(p => p.length),
  XPATH_TRANSCRIPTION_IN_TEI: "//tei:body/tei:div[@type='edition'][not(@subtype) or @subtype='transcription']",
  XPATH_TOKENS_IN_TEI: "//*[name()!='l'][name()!='lg'][name()!='lb'][name()!='cb'][name()!='milestone'][not(@type='textpart')]", // [@n='5']
  EXPECTED_TOKEN_TAGS: ['w', 'g', 'space', 'gap', 'orig'],
  // Special development mode if the site runs on that host.
  // Files will be fetched locally without github API if not authenticated.
  // Saving will be blocked if authenticated.
  // To simulate normal mode on your local machine,
  // access site on 127.0.0.1:3000 instead.
  DEVELOP_HOST: "localhost:3000",
}
SETTINGS.GITHUB_REPO_URL = `https://github.com/${SETTINGS.GITHUB_REPO_PATH}`
